"""Organization service for managing organizations and members."""

import logging
from datetime import UTC, datetime

from supabase import Client

from app.models.organization import (
    MemberApprovalRequest,
    MemberRoleUpdateRequest,
    OrganizationCreate,
    OrganizationInfo,
    OrganizationJoinRequest,
    OrganizationMemberInfo,
    OrganizationWithRole,
)

logger = logging.getLogger(__name__)


class OrganizationService:
    """Service for handling organization operations."""

    def __init__(self, supabase: Client):
        """Initialize organization service.

        :param supabase: Supabase client instance.
        """
        self.supabase = supabase

    async def create_organization(
        self, user_id: str, user_name: str, request: OrganizationCreate
    ) -> OrganizationInfo:
        """Create a new organization.

        :param user_id: Creator user UUID.
        :param user_name: Creator user name.
        :param request: Organization creation request.
        :return: Created organization information.
        :raises ValueError: If creation fails.
        """
        try:
            # Step 1: Create organization (org_code will be auto-generated by trigger)
            org_data = {
                "name": request.name,
                "created_by": user_id,
            }

            org_response = (
                self.supabase.table("organizations").insert(org_data).execute()
            )

            if not org_response.data:
                raise ValueError("Failed to create organization")

            org = org_response.data[0]
            org_id = org["id"]

            # Step 2: Add creator as creator role (auto-approved)
            member_data = {
                "org_id": org_id,
                "user_id": user_id,
                "role": "creator",
                "approved_at": datetime.now(UTC).isoformat(),
                "approved_by": user_id,  # Self-approved
            }

            self.supabase.table("org_members").insert(member_data).execute()

            # Step 3: Update user's current_org_id
            self.supabase.table("users").update({"current_org_id": org_id}).eq(
                "id", user_id
            ).execute()

            return OrganizationInfo(
                id=org["id"],
                name=org["name"],
                org_code=org["org_code"],
                created_by=org["created_by"],
                created_at=org["created_at"],
                updated_at=org["updated_at"],
            )

        except Exception as e:
            logger.error(f"Failed to create organization: {e}")
            raise ValueError(f"Failed to create organization: {e!s}")

    async def join_organization(
        self, user_id: str, request: OrganizationJoinRequest
    ) -> OrganizationInfo:
        """Request to join an existing organization.

        :param user_id: User UUID.
        :param request: Join request with org_code.
        :return: Organization information.
        :raises ValueError: If organization not found or join fails.
        """
        try:
            # Step 1: Find organization by code
            org_response = (
                self.supabase.table("organizations")
                .select("*")
                .eq("org_code", request.org_code.upper())
                .execute()
            )

            if not org_response.data:
                raise ValueError(
                    f"Organization not found with code: {request.org_code}"
                )

            org = org_response.data[0]
            org_id = org["id"]

            # Step 2: Check if user is already a member
            existing_member = (
                self.supabase.table("org_members")
                .select("*")
                .eq("org_id", org_id)
                .eq("user_id", user_id)
                .execute()
            )

            if existing_member.data:
                role = existing_member.data[0]["role"]
                if role != "pending":
                    raise ValueError("You are already a member of this organization")
                elif role == "pending":
                    raise ValueError(
                        "You already have a pending request for this organization"
                    )

            # Step 3: Create join request (pending approval)
            member_data = {
                "org_id": org_id,
                "user_id": user_id,
                "role": "pending",
            }

            self.supabase.table("org_members").insert(member_data).execute()

            return OrganizationInfo(
                id=org["id"],
                name=org["name"],
                org_code=org["org_code"],
                created_by=org["created_by"],
                created_at=org["created_at"],
                updated_at=org["updated_at"],
            )

        except Exception as e:
            logger.error(f"Failed to join organization: {e}")
            raise ValueError(f"Failed to join organization: {e!s}")

    async def get_user_organizations(self, user_id: str) -> list[OrganizationWithRole]:
        """Get all organizations user is a member of.

        :param user_id: User UUID.
        :return: List of organizations with user's role.
        """
        try:
            # Query org_members joined with organizations
            response = (
                self.supabase.table("org_members")
                .select("*, organizations(*)")
                .eq("user_id", user_id)
                .execute()
            )

            organizations = []
            for member in response.data:
                org = member["organizations"]
                organizations.append(
                    OrganizationWithRole(
                        id=org["id"],
                        name=org["name"],
                        org_code=org["org_code"],
                        my_role=member["role"],
                        created_at=org["created_at"],
                    )
                )

            return organizations

        except Exception as e:
            logger.error(f"Failed to get user organizations: {e}")
            raise ValueError(f"Failed to get user organizations: {e!s}")

    async def get_organization_members(
        self, org_id: str, user_id: str
    ) -> list[OrganizationMemberInfo]:
        """Get all members of an organization.

        :param org_id: Organization UUID.
        :param user_id: Requesting user UUID (must be member).
        :return: List of members with details.
        :raises ValueError: If user is not a member.
        """
        try:
            # Verify user is an approved member (not pending)
            member_check = (
                self.supabase.table("org_members")
                .select("role")
                .eq("org_id", org_id)
                .eq("user_id", user_id)
                .neq("role", "pending")
                .execute()
            )

            if not member_check.data:
                raise ValueError("You are not a member of this organization")

            # Query members
            response = (
                self.supabase.table("org_members")
                .select("*")
                .eq("org_id", org_id)
                .execute()
            )

            # Fetch user details separately
            members = []
            for member in response.data:
                user_response = (
                    self.supabase.table("users")
                    .select("name, email")
                    .eq("id", member["user_id"])
                    .execute()
                )

                user = user_response.data[0] if user_response.data else {"name": "Unknown", "email": ""}

                members.append(
                    OrganizationMemberInfo(
                        id=member["id"],
                        org_id=member["org_id"],
                        user_id=member["user_id"],
                        user_name=user["name"],
                        user_email=user["email"],
                        role=member["role"],
                        requested_at=member["requested_at"],
                        approved_at=member.get("approved_at"),
                        approved_by=member.get("approved_by"),
                    )
                )

            return members

        except Exception as e:
            logger.error(f"Failed to get organization members: {e}")
            raise ValueError(f"Failed to get organization members: {e!s}")

    async def approve_or_reject_member(
        self, org_id: str, admin_user_id: str, request: MemberApprovalRequest
    ) -> OrganizationMemberInfo:
        """Approve or reject a member join request.

        :param org_id: Organization UUID.
        :param admin_user_id: Admin user UUID performing the action.
        :param request: Approval request.
        :return: Updated member information.
        :raises ValueError: If user is not admin or member not found.
        """
        try:
            # Verify admin status and get approver's role
            admin_check = (
                self.supabase.table("org_members")
                .select("role")
                .eq("org_id", org_id)
                .eq("user_id", admin_user_id)
                .in_("role", ["creator", "admin"])
                .execute()
            )

            if not admin_check.data:
                raise ValueError("You do not have admin permissions")

            approver_role = admin_check.data[0]["role"]

            # Get member details
            member_response = (
                self.supabase.table("org_members")
                .select("*")
                .eq("id", request.member_id)
                .eq("org_id", org_id)
                .execute()
            )

            if not member_response.data:
                raise ValueError("Member not found")

            member = member_response.data[0]

            if member["role"] != "pending":
                raise ValueError(
                    f"Member role is {member['role']}, can only approve/reject pending members"
                )

            if request.action == "approve":
                # Determine approved role (default: interviewer)
                approved_role = request.approved_role or "interviewer"

                # Hierarchical permission check:
                # - Creator can approve as admin or interviewer
                # - Admin can only approve as interviewer
                if approved_role == "admin" and approver_role != "creator":
                    raise ValueError(
                        "Only organization creator can approve members as admin. "
                        "Regular admins can only approve as interviewer."
                    )

                # Check admin limit when approving as admin
                if approved_role == "admin":
                    admin_count = (
                        self.supabase.table("org_members")
                        .select("id", count="exact")
                        .eq("org_id", org_id)
                        .eq("role", "admin")
                        .execute()
                    )

                    if admin_count.count and admin_count.count >= 3:
                        raise ValueError("Maximum of 3 admins allowed per organization")

                # Approve: change role from 'pending' to approved role
                update_data = {
                    "role": approved_role,
                    "approved_at": datetime.now(UTC).isoformat(),
                    "approved_by": admin_user_id,
                }

                # Update member role
                self.supabase.table("org_members").update(update_data).eq(
                    "id", request.member_id
                ).execute()

                # Set as user's current_org_id if they don't have one
                user = (
                    self.supabase.table("users")
                    .select("current_org_id")
                    .eq("id", member["user_id"])
                    .execute()
                )

                if user.data and not user.data[0].get("current_org_id"):
                    self.supabase.table("users").update({"current_org_id": org_id}).eq(
                        "id", member["user_id"]
                    ).execute()
            else:
                # Reject: delete the pending request
                self.supabase.table("org_members").delete().eq(
                    "id", request.member_id
                ).execute()

                # Return early for rejection (member is deleted)
                return OrganizationMemberInfo(
                    id=member["id"],
                    org_id=member["org_id"],
                    user_id=member["user_id"],
                    user_name="",  # Don't need to fetch user data for deleted record
                    user_email="",
                    role="pending",  # Original role before deletion
                    requested_at=member["requested_at"],
                    approved_at=None,
                    approved_by=None,
                )

            # Re-fetch member data
            result = (
                self.supabase.table("org_members")
                .select("*")
                .eq("id", request.member_id)
                .execute()
            )

            member_data = result.data[0]

            # Fetch user details separately
            user_response = (
                self.supabase.table("users")
                .select("name, email")
                .eq("id", member_data["user_id"])
                .execute()
            )

            user_data = user_response.data[0] if user_response.data else {"name": "Unknown", "email": ""}

            return OrganizationMemberInfo(
                id=member_data["id"],
                org_id=member_data["org_id"],
                user_id=member_data["user_id"],
                user_name=user_data["name"],
                user_email=user_data["email"],
                role=member_data["role"],
                requested_at=member_data["requested_at"],
                approved_at=member_data.get("approved_at"),
                approved_by=member_data.get("approved_by"),
            )

        except Exception as e:
            logger.error(f"Failed to approve/reject member: {e}")
            raise ValueError(f"Failed to approve/reject member: {e!s}")

    async def update_member_role(
        self, org_id: str, admin_user_id: str, request: MemberRoleUpdateRequest
    ) -> OrganizationMemberInfo:
        """Update a member's role (admin only).

        :param org_id: Organization UUID.
        :param admin_user_id: Admin user UUID performing the action.
        :param request: Role update request.
        :return: Updated member information.
        :raises ValueError: If user is not admin or validation fails.
        """
        try:
            # Verify admin status and get admin's role
            admin_check = (
                self.supabase.table("org_members")
                .select("role")
                .eq("org_id", org_id)
                .eq("user_id", admin_user_id)
                .in_("role", ["creator", "admin"])
                .execute()
            )

            if not admin_check.data:
                raise ValueError("You do not have admin permissions")

            admin_role = admin_check.data[0]["role"]

            # Get member details
            member_response = (
                self.supabase.table("org_members")
                .select("*")
                .eq("id", request.member_id)
                .eq("org_id", org_id)
                .execute()
            )

            if not member_response.data:
                raise ValueError("Member not found")

            member = member_response.data[0]

            if member["role"] == "pending":
                raise ValueError("Cannot update role for pending members (approve them first)")

            # Hierarchical permission check:
            # - Creator can update to admin or interviewer
            # - Admin can only update to interviewer
            if request.new_role == "admin" and admin_role != "creator":
                raise ValueError(
                    "Only organization creator can promote members to admin. "
                    "Regular admins can only assign interviewer role."
                )

            # Check admin limit when promoting to admin
            if request.new_role == "admin":
                admin_count = (
                    self.supabase.table("org_members")
                    .select("id", count="exact")
                    .eq("org_id", org_id)
                    .eq("role", "admin")
                    .execute()
                )

                if admin_count.count and admin_count.count >= 3:
                    raise ValueError("Maximum of 3 admins allowed per organization")

            # Update role
            self.supabase.table("org_members").update({"role": request.new_role}).eq(
                "id", request.member_id
            ).execute()

            # Re-fetch member data
            result = (
                self.supabase.table("org_members")
                .select("*")
                .eq("id", request.member_id)
                .execute()
            )

            member_data = result.data[0]

            # Fetch user details separately
            user_response = (
                self.supabase.table("users")
                .select("name, email")
                .eq("id", member_data["user_id"])
                .execute()
            )

            user_data = user_response.data[0] if user_response.data else {"name": "Unknown", "email": ""}

            return OrganizationMemberInfo(
                id=member_data["id"],
                org_id=member_data["org_id"],
                user_id=member_data["user_id"],
                user_name=user_data["name"],
                user_email=user_data["email"],
                role=member_data["role"],
                requested_at=member_data["requested_at"],
                approved_at=member_data.get("approved_at"),
                approved_by=member_data.get("approved_by"),
            )

        except Exception as e:
            logger.error(f"Failed to update member role: {e}")
            raise ValueError(f"Failed to update member role: {e!s}")

    async def remove_member(
        self, org_id: str, admin_user_id: str, member_id: int
    ) -> None:
        """Remove a member from organization (admin only).

        :param org_id: Organization UUID.
        :param admin_user_id: Admin user UUID performing the action.
        :param member_id: Member record ID to remove.
        :raises ValueError: If user is not admin or validation fails.
        """
        try:
            # Verify admin status (creator or admin role)
            admin_check = (
                self.supabase.table("org_members")
                .select("role")
                .eq("org_id", org_id)
                .eq("user_id", admin_user_id)
                .in_("role", ["creator", "admin"])
                .execute()
            )

            if not admin_check.data:
                raise ValueError("You do not have admin permissions")

            # Get member to remove
            member_response = (
                self.supabase.table("org_members")
                .select("*")
                .eq("id", member_id)
                .eq("org_id", org_id)
                .execute()
            )

            if not member_response.data:
                raise ValueError("Member not found")

            member = member_response.data[0]

            # Check if trying to remove organization creator
            org = (
                self.supabase.table("organizations")
                .select("created_by")
                .eq("id", org_id)
                .execute()
            )

            if org.data and org.data[0]["created_by"] == member["user_id"]:
                raise ValueError("Cannot remove organization creator")

            # Delete member
            self.supabase.table("org_members").delete().eq("id", member_id).execute()

            # Clear current_org_id if this was the user's current org
            user = (
                self.supabase.table("users")
                .select("current_org_id")
                .eq("id", member["user_id"])
                .execute()
            )

            if user.data and user.data[0].get("current_org_id") == org_id:
                self.supabase.table("users").update({"current_org_id": None}).eq(
                    "id", member["user_id"]
                ).execute()

        except Exception as e:
            logger.error(f"Failed to remove member: {e}")
            raise ValueError(f"Failed to remove member: {e!s}")
